#!/bin/bash
	systemd-cat rsync -arvslm -e 'ssh -i /home/tknomanzr/.ssh/bl_rsa' --ipv4 --delete --delete-excluded --exclude-from=/home/tknomanzr/.config/backup/backup-excludes \
	--log-file=/home/tknomanzr/.config/backup/backup.log / 192.168.1.4:/shares/Public/backups/wtfbox-bl
exit 0
