#!/bin/bash
	systemd-cat rsync -arvslm -e 'ssh -i /home/user/.ssh/id_rsa' --ipv4 --delete --delete-excluded --exclude-from=$HOME/.config/backup/backup-excludes \
	--log-file=$HOME/.config/backup/backup.log / ip_address:/path_to_share
exit 0
