#!/bin/bash
readarray -t updates <<< "$(apt list --upgradable 2>/dev/null)"
numupdates=$((${#updates[*]}-1))
echo $numupdates "updates available."
echo "\${hr 1}"
printf -- "%s\n" "${updates[@]:1:20}"
if [ $numupdates -eq "0" ]; then
	echo "No packages to update at this time."
elif [ $numupdates -gt "20" ]; then
	echo -e "\${hr 1}"
	echo "\$alignr More Updates Available..."
fi
exit 0;
