#!/bin/bash
# A script that will allow the user to semi-automatically run 
# sudo apt-get upate
# sudo apt list --upgradable
# sudo apt-get upgrade
# This script can be used as is but was more designed
# to work with the executor in tint2
# Large part of this script have already been produced by the
# BunsenLabs development team.
#
# Author: William Bradley
# Email: webradley9929@gmail.com
# Git Location: https://github.com/tknomanzr/scripts/tree/master/list-updates
# Date: 8/22/2017
#----------------------------------------------------------------------------

BL_COMMON_LIBDIR='/usr/lib/bunsen/common'
if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
    exit 1
fi
clear
echo "Bunsenlabs Update|Upgrade script"
echo "---------------------------------------------------------------------------"
echo "This script can be run standalone or via an executor in tint2"
echo "This script will update/upgrade your Bunsenlabs system."
echo
read -rsn1 -p"Would you like to proceed with this update/upgrade of your system? [Y|n] " $REPLY;echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
	# Test for vaild internet and do the update
	connectiontest 1
	safeUpdate
else
	echo "You still have pending package upgrades." 
	echo "Rerun this script to upgrade your system asap."
	exit 0
fi
# Get the list of updates
readarray -t updates <<< "$(apt list --upgradable 2>/dev/null)"

# Get the number of updates
numupdates=$((${#updates[*]}-1))

echo "You have $numupdates pending updates"
safeUpgrade
# Wait for input to close terminal
read -p"Press any key to close this terminal."
exit 0
